spring:
  application:
    name: HubSpot Integration

server:
  port: 8080

hubspot:
  client-id: ${HUBSPOT_CLIENT_ID}
  client-secret: ${HUBSPOT_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/oauth/callback
  auth-url: https://app.hubspot.com/oauth/authorize
  token-url: https://api.hubapi.com/oauth/v1/token
  scopes: contacts

logging:
  level:
    root: INFO
    com.nicoletti: DEBUG